### ISSUE TITLE
Scribus 1.6 formula plan

### ISSUE THREAD

**Issue by luzpaz** [scribusproject/homebrew-scribus#6]
Once Scribus v1.6 comes out, update formula and submit scribus.rb to official homebrew repo 
The formula should contain a
- [x] --HEAD section
- [ ] --without section
- [ ] patch section
- [x] test block 
- [ ] compile specific revisions (https://github.com/scribusproject/homebrew-scribus/issues/11 & https://github.com/scribusproject/homebrew-scribus/issues/14)
- [ ] Specify GUI language flag (https://github.com/scribusproject/homebrew-scribus /issues/5)
- [ ] Output appropriate messaging that are more informative (https://github.com/scribusproject/homebrew-scribus/issues/4)
## Gist in progress:

https://gist.github.com/luzpaz/647414b7470b9e78b851

**Comment by luzpaz** [comment]
See https://github.com/Homebrew/homebrew-science/blob/master/octave.rb
